### ISSUE TITLE
Userscripts end in .user.js not .js

### ISSUE THREAD

**Issue by Martii** [DaTechNinja/bmo-investorline-infinite-session#1]
Your script won't be served correctly on OUJS like you have it. You need to rename the .js file to a .user.js like this:

> git mv bmo-investorline-infinite-session.js bmo-investorline-infinite-session.user.js

... then do your usual push to GH...

... and then reimport it into OUJS. If there is a cross-site compatibility with libraries wanted you need to use the Userscript metadata block with `@exclude *` which I assume isn't what you are looking for since this appears to be a full Userscript. So a simple rename and reimport will fix this for you. Your library has been deleted as you and you will be reable to upload it again with the proper file name structure.

Thanks,
OUJS Admin

**Comment by Martii** [comment]
P.S. Ensure that you use:

``` js
// ==UserScript==

// ...

// ==/UserScript==

``` 

and **not** `// ==OpenUserJS==` open/close pairing for a regular Userscript too otherwise your `@require`s won't ever be downloaded. e.g. just like you have in [your current source here on GH](https://github.com/DaTechNinja/bmo-investorline-infinite-session/blob/bfcc621a0126ef10481c6390de23ee31d52b90c3/bmo-investorline-infinite-session.js#L1-L18).

**Comment by DaTechNinja** [comment]
Hey, thanks for the information, I was wondering why I was getting import errors. I'm new to publishing to your site. I'll make the changes and re-import.

**Comment by DaTechNinja** [comment]
@Martii Thanks for the help, I've made the changes and re-imported the script and keep this in mind for future publishes. Please let me know if there are any other problems. Have yourself a Happy New Year!
